### ISSUE TITLE
Doesn't work with new v4 API

### ISSUE THREAD

**Issue by Miicroo** [persandstrom/python-vasttrafik#4]
Got a [comment](https://github.com/Miicroo/ha-vasttrafik/issues/1) on a homeassistant component using this lib: 

> Neither this nor the core vasttrafik sensor works with the new v4 API. The old API will be shutdown in a few months.

**Comment by persandstrom** [comment]
Hi,

I have not been using this for a long time and will not adapt it to any new version of the API.  I believe it would be easiest if someone either forked this project or created a new project for v4.

**Comment by Miicroo** [comment]
@persandstrom Perfect, I will try to make the necessary changes in a fork! Is it possible to release the new version under the same pypi-project, or is that tied to you (or this repo)? Never done it before so a bit uncertain what I would need

**Comment by persandstrom** [comment]
I don't know. I'll Investigate if it is possible to transfer ownership of a pypi project

**Comment by persandstrom** [comment]
I need your pypi username

**Comment by Miicroo** [comment]
@persandstrom my username is Miicroo on pypi

**Comment by Miicroo** [comment]
Can close this now, verified working! Fix on its way into HA!
